esphome:
  name: wf183de_sensor
  platform: ESP32
  board: esp32-c3-devkitm-1

external_components:
  - source: "./wf183de_sensor.h"

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: false

sensor:
  - platform: custom
    lambda: |-
      auto *wf183de_sensor = new WF183DESensor();
      App.register_component(wf183de_sensor);
      return {wf183de_sensor->get_temperature_sensor(), wf183de_sensor->get_pressure_sensor()};
    sensors:
      - name: "WF183DE Temperature"
        unit_of_measurement: "°C"
        accuracy_decimals: 1
      - name: "WF183DE Pressure"
        unit_of_measurement: "kPa"
        accuracy_decimals: 1
